#!/bin/bash
set -euo pipefail

# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [[ $# -lt 1 ]]; then
    echo "Usage: brew gomod github.com/foo/bar [...]"
    exit 1
fi

NAME=$(basename "$1")
VERSION=$(date '+%Y-%m-%d')

brew list "gomod-$NAME" >/dev/null 2>&1 && \
    brew unlink "gomod-$NAME" 

ROOT="$(brew --prefix)/Cellar/gomod-$NAME/$VERSION"
export GOBIN="$ROOT/bin"

mkdir -p "$ROOT/libexec/mod"
cd "$ROOT/libexec/mod"

go mod init "gomod-$NAME/$VERSION"
go get "$@"

brew link "gomod-$NAME"
